config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # controllers: {
  #       sessions: 'users/sessions'
  #     }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :animals do
    resources :adoptions, only: :create
  end
  resources :adoptions, only: [:show, :index]
  resources :pages

  get '/search', to: 'pages#search', as: 'animal_search'
  
end

app/views/shared/_footer.html.erb
<footer class="mainfooter">
  <div class="footer-middle">
  <div class="container">
    <div class="row">
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Quer um amigo?</h4>
          <ul class="list-unstyled">
           <a href="https://medium.com/blog-da-bere/o-que-%C3%A9-ado%C3%A7%C3%A3o-respons%C3%A1vel-e87c09a537e9"><div class="button-footer"><li>Adoção responsável</li></div></a>
            <a href="#"><div class="button-footer"><li>Pocure seu amigo</li></div></a>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Melhores Amigos</h4>
          <ul class="list-unstyled">
            <a href="https://www.casapraticaqualita.com.br/noticia/5-cuidados-para-ter-antes-de-adotar-um-cachorro-ou-um-gato_a1827/1"><div class="button-footer"><li>Dicas e cuidados</li></div></a>
            <a href="https://www.worldanimalprotection.org.br/vidas-melhores-para-caes/guarda-responsavel"><div class="button-footer"><li>Guarda responsável</li></div></a>
          </ul>
        </div>
      </div>
      <div class="col-md-3 col-sm-6">
        <!--Column1-->
        <div class="footer-pad">
          <h4>Quem somos</h4>
          <ul class="list-unstyled">
            <a href="#"><div class="button-footer"><li>Sobre nós</li></div></a>
            <a href="#"><div class="button-footer"><li>Fale conosco</li></div></a>
          </ul>
        </div>
      </div>
    	<div class="col-md-3">
    		<h4>Nos siga também</h4>
            <ul class="social-network social-circle">
            <li><a href="#" class="icoFacebook" title="Facebook"><i class="fab fa-facebook"></i></i></a></li>
             <li><a href="#" class="icoLinkedin" title="Linkedin"><i class="fab fa-instagram"></i></a></li>
            </ul>				
		</div>
    </div>
	<div class="row">
		<div class="col-md-12 copy">
			<p class="text-center">&copy; Copyright 2020 - Farejadores.  All rights reserved.</p>
		</div>
	</div>


  </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag("logo.jpg") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if current_user %>
       <li class="nav-item">
          <%= link_to current_user.name, user_session_path, class: "nav-link" %>
        </li>
      <li class="nav-item dropdown">
        <% if current_user.photo.attached? %>
          <%= cl_image_tag current_user.photo.key, transformation: [{width: 55, height: 55, gravity: "face", radius: "max", crop: "fill", quality: 80}, {width: 55, crop: "scale"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= image_tag "https://st3.depositphotos.com/9412676/12748/v/950/depositphotos_127481014-stock-illustration-standard-user-icon-set.jpg", transformation: [{width: 55, height: 55, gravity: "face", radius: "max", crop: "fill", quality: 80}, {width: 55, crop: "scale"}], class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "My Pets", animals_path, class: "dropdown-item" %>
          <%= link_to "New Pet", new_animal_path, class: "dropdown-item" %>
          <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>

      <% else%>

        <li class="nav-item">
          <%= link_to "Login/SignUp", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>

    </ul>
  </div>
</div>