config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # controllers: {
  #       sessions: 'users/sessions'
  #     }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :animals do
    resources :adoptions, only: :create
  end
  resources :adoptions, only: [:show, :index]
  resources :pages

  get '/search', to: 'pages#search', as: 'animal_search'
  
end

app/models/animal.rb
class Animal < ApplicationRecord
  has_one_attached :photo
  belongs_to :owner, class_name: 'User', foreign_key: 'user_id'
  SPECIES = %w(Cachorro Gato)
  validates :specie, inclusion: { in: SPECIES }
  SIZE = %w(Pequeno Medio Grande)
  validates :size, inclusion: { in: SIZE }
  SEX = %w(Macho Fêmea)
  validates :sex, inclusion: { in: SEX }
  YESNO = %w(Sim Não)
  validates :health_castrated, inclusion: { in: YESNO }
  validates :health_vaccinated, inclusion: { in: YESNO }
  validates :health_dewormed, inclusion: { in: YESNO }
  validates :health_special, inclusion: { in: YESNO }
  validates :photo, presence: true
  AGE = %w(Filhote Adulto Idoso)
  validates :description, inclusion: { in: AGE }
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :search]
  before_action :set_animal, only: %i[show edit update destroy]

  def index
    @animals = Animal.where(adopted: false, owner: current_user)
  end

  def show
    @adoption = Adoption.new
  end

  def new
    @animal = Animal.new
  end

  def edit
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.owner = current_user
    if @animal.save
      redirect_to animal_path(@animal)
    else
      render :new
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    if @animal.update(animal_params)
      redirect_to animal_path(@animal)
    else
      render :edit
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    redirect_to animals_path
  end

  private

  def set_animal
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:photo,
                                   :specie,
     								               :size,
     								               :location,
     								               :name,
     								               :sex,
      							               :health_castrated,
      						              	 :health_vaccinated,
      							               :health_dewormed,
                                   :health_special,
                                   :description)
  end
end

app/views/animals/_form.html.erb
<div class="container">
	<%= simple_form_for @animal do |f| %>
	  <%= f.input :photo, as: :file %>
		<%= f.input :specie, label: 'Qual a espécie do animal?', collection: Animal::SPECIES %>		
		<%= f.input :name, label: 'Qual o nome do animal?' %>
		<%= f.input :description, label: 'Qual a idade do animal?', collection: Animal::AGE %>
		<%= f.input :size, label: 'Qual o porte?', collection: Animal::SIZE %>
		<%= f.input :location, label: 'Onde ele(a) está localizado?' %>
		<%= f.input :sex, label: 'Qual o sexo do animal?', collection: Animal::SEX %>
		<%= f.input :health_castrated, label: 'Está castrado?', collection: Animal::YESNO %>
		<%= f.input :health_vaccinated, label: 'Está vacinado?', collection: Animal::YESNO %>
		<%= f.input :health_dewormed, label: 'Está vermifugado?', collection: Animal::YESNO %>
		<%= f.input :health_special, label: 'Precisa de cuidados especiais?', collection: Animal::YESNO %>
		<%= f.submit 'Publicar' %>
	<% end %>
</div>

app/views/animals/edit.html.erb
<h1>Edit Animal</h1>

<%= render 'form', animal: @animal %>

app/views/animals/index.html.erb
<div class="container mt-4">
	<h1>Animais para adoção</h1>
	<div class="cards-container">
	  <div class="cards">
		<% @animals.each do |animal| %>
	      <% if animal.adopted == false %>
	        <% if animal.photo.attached? %>
	          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path animal.photo.key, height: 300, width: 400, gravity: :auto, crop: :fill %>')">
	            <%= link_to animal.name.capitalize, animal_path(animal), class: "btn btn-secondary pet_tag" %>
	          </div>
	        <% end %>
	      <% end %>  
	    <% end %>
	  </div>
	</div>
</div>

app/views/animals/new.html.erb
<div class="borda_texto" id="fixed">
  <span><div id='typed-text'></div></span>
</div>

<div class= "container", "text" style="width:35%;">

  <%= render 'form', animal: @animal %>

</div>

app/views/animals/show.html.erb
<%= link_to "voltar", animals_path, class: "btn btn-secondary m-3" %>
<div class="container">
  <div class="d-flex justify-content-center">
      <div style="padding-bottom: 40px;">
        <div class="clear">
          <h1 class="animal-name"> <strong><%= @animal.name %></strong> </h1>
        </div>
        <div class="row">
            <div class="col-lg-8 col-md-8 animal-photo">
              <%= cl_image_tag @animal.photo.key, height: 600, width: 700, gravity: :auto, crop: :fill %>
            </div>

            <div class="col-lg-4 col-md-4">
                <div class="organizer">
                    <div class="card-body">
                      
                      <div class="clear-box" style="padding: 20px; margin-bottom: 20px;">
                        <p><strong>DADOS GERAIS</strong></p>
                        <ul class="pet-check">
                          <p class="fas fa-paw"> <i style="color:red;">Espécie:  </i><i style="color:black;"><%= @animal.specie %></i></p>
                          <p class="fas fa-paw"> <i style="color:red;">Porte:  </i><i style="color:black;"><%= @animal.size %></i></p>
                          <p class="fas fa-paw"> <i style="color:red;">Localização: </i><i style="color:black;"><%= @animal.location.capitalize %></i></p>
                          <p class="fas fa-paw"> <i style="color:red;">Sexo:  </i><i style="color:black;"><%= @animal.sex %></i></p>
                          <p class="fas fa-paw"> <i style="color:red;">Castrado?  </i><i style="color:black;"><%= @animal.health_castrated %></i></p>
                          <p class="fas fa-paw"> <i style="color:red;">Vacinado?  </i><i style="color:black;"><%= @animal.health_vaccinated %></i></p>
                          <p class="fas fa-paw"> <i style="color:red;">Vermifugado?  </i><i style="color:black;"><%= @animal.health_dewormed %></i></p>
                          <p class="fas fa-paw"> <i style="color:red;">Necessita de cuidados especiais?  </i><i style="color:black;"><%= @animal.health_special %></i></p>
                        </ul>

                        <% if @animal.owner != current_user %>
                          <%= simple_form_for [@animal, @adoption] do |f| %>
                            <%= f.submit 'Quero adotar!', class: "btn btn-success btn-lg btn-block"%>
                          <% end %>
                        <% end %>

                      </div>
                      
                      <% if @animal.owner == current_user %>
                        <div class="row d-flex justify-content-around">
                          <%= link_to edit_animal_path(@animal) do  %>
                          <i class="fas fa-edit"></i>
                          <% end %>
                          <%= link_to animal_path(@animal), method: :delete, data: {confirm: "Are you sure?"} do %>
                          <i class="far fa-trash-alt"> </i>
                          <% end %>
                        </div>
                      <% end %>
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>

    <div class="container">
        <div class="card-pet-info">
          <div class="col-md-10">
            <div class="about" align="justify">
              <h3><strong>A história de <%= @animal.name %></strong></h3>
              <br>
              <br>
              
              <p>Olá,</p>

              <p>Meu nome é <%= @animal.name %>, sou um <%= @animal.specie %> de porte <%= @animal.size %>, que adora um carinho, gosto de brincar com outros <%= @animal.specie.pluralize %>, sou tranquilo e companheiro. falam que sou muito bonzinho e não entendem como puderam me abandonar, depois de perder meu lar, tive que passar um tempo nas ruas.</p>
              <p>Tudo o que quero é encontrar uma família que me queira e que me ame assim como eu irei amá-la! Apesar de toda a dor que passei, o que mais tenho dentro de mim é amor e carinho, que espero poder te dar!</p>
              <p>Se quiser ser meu dono, clique no Botão Quero adotar.</p>
              <p>Moro em <%= @animal.location.capitalize %>.</p>
              <p>Do seu futuro melhor amigo, 
                <br><%= @animal.name %>.
              </p>

              <p><strong>Descrição do Usuário: </strong><%= @animal.description %></p>
            </div>
          </div>
        </div>
    </div>
  </div>   
</div>